export enum ErrorCode {
  CNPJ_INVALIDO = 'CNPJ_INVALIDO',
  CNPJ_NAO_ENCONTRADO = 'CNPJ_NAO_ENCONTRADO',
  BANCO_INDISPONIVEL = 'BANCO_INDISPONIVEL',
  DOWNLOAD_FALHOU = 'DOWNLOAD_FALHOU',
  IMPORTACAO_FALHOU = 'IMPORTACAO_FALHOU',
  PARAMETROS_INVALIDOS = 'PARAMETROS_INVALIDOS',
}
