apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cnpj-api-hpa
  namespace: cnpj
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cnpj-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
